- name: Install basic packages
  become: yes
  yum:
    name: {{ item }}
    state: latest
  with_items:
    - git
    - curl
    - wget
    - tree
    - epel-release.noarch
    - python-pip

- name: install httplib2
  pip:
    name=httplib2 state=latest
