- name: install ePages 6 latest
  command: ~/epages-infra/scripts/epages/install_epages.sh -p

- name: Chmod start_epages.sh
  command: chmod 777 ~/3rdPartyTools/Scripts/infrastructure/epages_docker/start_epages.sh

- name: Start ePages on Docker container
  command: ~/3rdPartyTools/Scripts/infrastructure/epages_docker/start_epages.sh -i {{ dockerHost }}
