---

- name: Deactivate firewall
  command: "{{item}}"
  with_items:
   - "service ip6tables save"
   - "service ip6tables stop"
   - "chkconfig ip6tables off"
   - "service iptables save"
   - "service iptables stop"
   - "chkconfig iptables off"
