- name: Download Java
  command: "wget -q -O /opt/jdk-8u72-linux-x64.tar.gz --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u72-b15/jdk-8u72-linux-x64.tar.gz creates=/opt/jdk-8u72-linux-x64.tar.gz"

- name: Unpack archive
  command: "tar -zxf /opt/jdk-8u72-linux-x64.tar.gz -C /opt creates=/opt/jdk1.8.0_72"

- name: Install alternatives
  command: alternatives --install /usr/bin/java java /opt/jdk1.8.0_72/bin/java 2

- name: Fix ownership
  file: state=directory path=/opt/jdk1.8.0_72 owner=root group=root recurse=yes

- name: correct java version selected
  alternatives: name=java path=/opt/jdk1.8.0_72/bin/java

- name: Clean up
  file: state=absent path=/opt/jdk-8u5-linux-x64.tar.gz
