
- name: Clone ESF repo
  git:
    repo: git@github.com:ePages-de/esf.git
    dest: esf
    update: no
    accept_hostkey: true

- name: Gradle distribution
  command: esf/gradlew dist -p esf/

- name: build esf image
  docker_image:
    path=esf
    name=esf
    state=present
