- name: install docker py
  pip:
    name=docker-py version=1.4.0

- name: build centos image
  docker_image:
    path=docker/centos
    name=epages_centos
    state=present

- name: run centos container
  docker:
    name=centos
    image=epages_centos
    tty=yes
    state=started
    ports="80:80,2222:22,443:443,8088:8088"
    volumes="/root/3rdPartyTools:/root/3rdPartyTools"
