- name: install commons
  yum:
    name={{ item }}
  with_items:
    - tree
    - nano
    - python-pip

- name: install httplib2
  pip:
    name=httplib2

- name: Update known_hosts
  command=ssh-keygen -R [localhost]:2222
