- name: Add Docker repository into source list
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-wily main' state=present

- name: install commons
  apt:
    name={{ item }}
  with_items:
    - openssh-server
    - openjdk-8-jdk
    - tree
    - nano
    - docker-engine

- name: Install pip
  easy_install: name=pip

- name: install docker py
  pip:
    name=docker-py version=1.4.0
