- name: Add Docker repository into source list
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-wily main' state=present

- name: Install commons
  apt:
    name={{ item }}
    force=yes
  with_items:
    - openssh-server
    - openjdk-8-jdk
    - tree
    - nano
    - bridge-utils
    - docker-engine

- name: Install pip
  easy_install: name=pip

- name: Install docker py
  pip:
    name=docker-py version=1.4.0

- name: Ca-certificates-java
  shell: "/var/lib/dpkg/info/ca-certificates-java.postinst configure"
