- name: Install docker-io
  yum:
    name=docker-io

- name: install docker py
  pip:
    name=docker-py version=1.4.0

- name: Enable IP Forwarding on the fly
  command=sysctl -w net.ipv4.ip_forward=1
